apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-app
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.labels.app }}